spring:
 application:
  name:
   gateway
 cloud:
  gateway:
   routes:
   - id: ship-service-route
     uri: lb://ship-service
     predicates:
     - Path=/fleet/**
   - id: menu-service-route
     uri: lb://menu-service
     predicates:
     - Path=/menu/**

server:
 port: 9000

eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka